### ISSUE TITLE
BUG:  Mission "Empire: Escort Empire Raven" will not offer

### ISSUE THREAD

**Issue by lumbar527** [OcelotWalrus/Cromha-Expansion-plugin#108]
**Describe the bug**
The mission `Empire: Escort Empire Raven` will not offer, even though I have the previous mission done. (I cheated to get the recruitment mission offered, turning the `random < 2` into `random < 100`)

**To Reproduce**
1. Get the recruitment/humanitarian mission.
2. Do it.
3. Get no mission.

**Expected behavior**
I expected to get the mission.

**Screenshots**
<img width="1680" alt="Screen Shot 2023-07-16 at 11 04 53 AM" src="https://github.com/OcelotWalrus/Cromha-Expansion-plugin/assets/125756761/30520213-ca6b-40f0-a6a2-f317b3501d38">
Not very helpful, but this shows I got the mission.

**Game Logs**
First of all, some errors I copied from `errors.txt`.
[related errors.txt](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/files/12064663/related.errors.txt)
`errors.txt`:
[errors.txt](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/files/12064667/errors.txt)
Saves (The first one I had traveled some after completing the mission):
[Fire Hawkins.txt](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/files/12064672/Fire.Hawkins.txt)
[test test.txt](https://github.com/OcelotWalrus/Cromha-Expansion-plugin/files/12064673/test.test.txt)

**Additional context**
Just going to restate above: I cheated and edited the plugin data files to make the chance of getting the mission 100%.

**Comment by OcelotWalrus** [comment]
It's normal and it has been fixed. Make sure you have the latest version. So recently I removed the Empire Shield Cores and create the Quatalant Shields. But it didn't updated the ships yet so it's why it don't give the mission: the wardragon had an outfit called "Empire Shielding Core" but it wasn't existant since I replaced it. It should be fixed now since I updated all the ship.
